export const ExampleContractAbi = [
    {
        type: "event",
        name: "Transfer",
        inputs: [{ name: "value", type: "uint256" }]
    }
] as const;

// contract ABIs generated by Foundry must be copied into TypeScript (.ts) source files