export const RewardContractAbi = [
    {
      "type": "event",
      "name": "RewardClaimed",
      "inputs": [
        {"name": "user", "type": "address", "indexed": true},
        {"name": "amount", "type": "uint256", "indexed": false}
      ]
    }
] as const;

// contract ABIs generated by Foundry must be copied into TypeScript (.ts) source files